# Generated by Django 5.0.1 on 2024-01-06 04:43

import django.db.models.deletion
import game.models.company_game
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyObjectId', models.IntegerField()),
                ('name', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='CloseDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isWholeday', models.BooleanField(default=True)),
                ('drawTypes', models.CharField(max_length=30)),
                ('companyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameSettings', models.JSONField(default=game.models.company_game.CompanyGame.game_settings_default, verbose_name='GameSettings')),
                ('companyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.company', verbose_name='CompanyId')),
            ],
        ),
        migrations.CreateModel(
            name='GameDrawType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('startTime', models.TimeField()),
                ('cutOff', models.TimeField()),
                ('companyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.company', verbose_name='CompanyId')),
            ],
        ),
        migrations.CreateModel(
            name='GameSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('drawResultId', models.IntegerField()),
                ('companyGameId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.companygame', verbose_name='CompanyGameId')),
                ('gameDrawTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gamedrawtype', verbose_name='GameDrawType')),
            ],
        ),
    ]
