# Generated by Django 5.0.1 on 2024-01-24 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companygame',
            name='companyId',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='closedate',
            name='companyId',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='gamedrawtype',
            name='companyId',
            field=models.CharField(max_length=40),
        ),
        migrations.AddField(
            model_name='companygame',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DrawResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=30)),
                ('amount', models.FloatField()),
                ('noOfWinners', models.IntegerField()),
                ('isDeleted', models.BooleanField(default=False)),
                ('gameScheduleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gameschedule', verbose_name='GameScheduleId')),
            ],
        ),
        migrations.CreateModel(
            name='DrawResultWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountInfoId', models.CharField(max_length=40)),
                ('amount', models.FloatField()),
                ('betInfoId', models.CharField(max_length=40)),
                ('isDeleted', models.BooleanField(default=False)),
                ('drawResultId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.drawresult', verbose_name='DrawResultId')),
            ],
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
