# Generated by Django 5.0.1 on 2024-01-24 06:20

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_companygame_companyid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='gamedrawtype',
            old_name='cutOff',
            new_name='endCutOff',
        ),
        migrations.RenameField(
            model_name='gamedrawtype',
            old_name='name',
            new_name='gameDrawTypeName',
        ),
        migrations.RenameField(
            model_name='gamedrawtype',
            old_name='startTime',
            new_name='openSchedule',
        ),
        migrations.RemoveField(
            model_name='closedate',
            name='drawTypes',
        ),
        migrations.AddField(
            model_name='closedate',
            name='closedDrawTypes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='closedate',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamedrawtype',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameschedule',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gameschedule',
            name='drawResultId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.drawresult', verbose_name='DrawResultId'),
        ),
    ]
