# Generated by Django 5.0.1 on 2024-01-24 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_rename_cutoff_gamedrawtype_endcutoff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companygame',
            name='gameId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.game', verbose_name='GameId'),
            preserve_default=False,
        ),
    ]
