# Generated by Django 5.0.1 on 2024-01-24 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_companygame_gameid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companygame',
            name='gameId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game', verbose_name='Game'),
        ),
        migrations.AlterField(
            model_name='drawresult',
            name='gameScheduleId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gameschedule', verbose_name='GameSchedule'),
        ),
        migrations.AlterField(
            model_name='drawresultwinner',
            name='drawResultId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.drawresult', verbose_name='DrawResult'),
        ),
        migrations.AlterField(
            model_name='gameschedule',
            name='companyGameId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.companygame', verbose_name='CompanyGame'),
        ),
        migrations.AlterField(
            model_name='gameschedule',
            name='drawResultId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.drawresult', verbose_name='DrawResult'),
        ),
    ]
