# Generated by Django 5.0.1 on 2024-01-24 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_companygame_gameid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameschedule',
            old_name='companyGameId',
            new_name='companyGame',
        ),
        migrations.RenameField(
            model_name='gameschedule',
            old_name='drawResultId',
            new_name='drawResult',
        ),
        migrations.RenameField(
            model_name='gameschedule',
            old_name='gameDrawTypeId',
            new_name='gameDrawType',
        ),
    ]
