# Generated by Django 5.0.1 on 2024-01-24 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_rename_companygameid_gameschedule_companygame_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companygame',
            old_name='gameId',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='drawresult',
            old_name='gameScheduleId',
            new_name='gameSchedule',
        ),
        migrations.RenameField(
            model_name='drawresultwinner',
            old_name='drawResultId',
            new_name='drawResult',
        ),
    ]
