# Generated by Django 5.0.1 on 2024-01-25 01:44

import game.models.game
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_rename_gameid_companygame_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameMechanics',
            field=models.JSONField(default=game.models.game.Game.game_mechanics_default, verbose_name='GameMechanics'),
        ),
        migrations.AddField(
            model_name='game',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
