# Generated by Django 5.0.1 on 2024-01-26 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_game_gamemechanics_game_isdeleted_game_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closedate',
            name='closedDrawTypes',
        ),
        migrations.AddField(
            model_name='closedate',
            name='closedDrawType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.gamedrawtype', verbose_name='GameDrawType'),
        ),
        migrations.AddField(
            model_name='closedate',
            name='date',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
    ]
