# Generated by Django 5.0.1 on 2024-01-26 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_remove_closedate_closeddrawtypes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameschedule',
            name='drawResult',
        ),
    ]
