# Generated by Django 5.0.1 on 2024-01-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_remove_gameschedule_drawresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionNumber', models.CharField(max_length=16)),
                ('orderId', models.BigIntegerField()),
                ('totalAmount', models.FloatField()),
                ('dateOfTransaction', models.DateField()),
                ('accountId', models.BigIntegerField()),
                ('numberOfBets', models.IntegerField()),
                ('betType', models.IntegerField()),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
    ]
