# Generated by Django 5.0.1 on 2024-01-26 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_prizepool'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('orderItemId', models.BigIntegerField()),
                ('amount', models.IntegerField()),
                ('transactionDate', models.DateField()),
                ('isDeleted', models.BooleanField(default=False)),
                ('companyGame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.companygame', verbose_name='CompanyGame')),
                ('gameSchedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gameschedule', verbose_name='GameSchedule')),
            ],
        ),
    ]
