# Generated by Django 5.0.1 on 2024-01-26 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_betitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='betitem',
            name='betTransaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.bettransaction', verbose_name='BetTransaction'),
            preserve_default=False,
        ),
    ]
