# Generated by Django 5.0.1 on 2024-01-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_betitem_bettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedrawtype',
            name='drawTime',
            field=models.TimeField(default='10:00:00'),
            preserve_default=False,
        ),
    ]
