# Generated by Django 5.0.1 on 2024-02-01 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_gamedrawtype_drawtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameschedule',
            name='endCutOff',
            field=models.TimeField(default='13:03:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameschedule',
            name='openSchedule',
            field=models.TimeField(default='13:03:00'),
            preserve_default=False,
        ),
    ]
