# Generated by Django 5.0.1 on 2024-02-03 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_gameschedule_endcutoff_gameschedule_openschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betitem',
            name='betTransaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='betItem', to='game.bettransaction'),
        ),
        migrations.AlterField(
            model_name='betitem',
            name='companyGame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='betItem', to='game.companygame'),
        ),
        migrations.AlterField(
            model_name='betitem',
            name='gameSchedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='betItem', to='game.gameschedule'),
        ),
        migrations.AlterField(
            model_name='betitem',
            name='value',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='gameschedule',
            name='companyGame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameSchedule', to='game.companygame'),
        ),
        migrations.AlterField(
            model_name='gameschedule',
            name='gameDrawType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameSchedule', to='game.gamedrawtype'),
        ),
    ]
