# Generated by Django 5.0.1 on 2024-02-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_gameschedule_endcutoff_gameschedule_openschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameschedule',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
