# Generated by Django 5.0.1 on 2024-02-03 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_alter_betitem_bettransaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawresultwinner',
            name='betInfoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawResultWinner', to='game.betitem'),
        ),
        migrations.AlterField(
            model_name='drawresultwinner',
            name='drawResult',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawResultWinner', to='game.drawresult'),
        ),
    ]
