# Generated by Django 5.0.1 on 2024-02-03 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_alter_drawresultwinner_betinfoid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drawresultwinner',
            old_name='betInfoId',
            new_name='betInfo',
        ),
    ]
