# Generated by Django 5.0.1 on 2024-02-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_rename_betinfoid_drawresultwinner_betinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawresultwinner',
            name='isQuasi',
            field=models.BooleanField(default=False),
        ),
    ]
