# Generated by Django 5.0.1 on 2024-02-06 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_gameschedule_status'),
        ('game', '0020_drawresultwinner_isquasi'),
    ]

    operations = [
    ]
