# Generated by Django 5.0.1 on 2024-02-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_merge_20240206_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawresult',
            name='noOfQuasiWinners',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
