# Generated by Django 5.0.1 on 2024-02-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_drawresult_noofquasiwinners'),
    ]

    operations = [
        migrations.AddField(
            model_name='companygame',
            name='livestream',
            field=models.URLField(null=True),
        ),
    ]
