# Generated by Django 5.0.1 on 2024-02-10 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_drawresult_noofquasiwinners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closedate',
            name='companyId',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='companygame',
            name='companyId',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='drawresultwinner',
            name='accountInfoId',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='gamedrawtype',
            name='companyId',
            field=models.UUIDField(),
        ),
    ]
