# Generated by Django 5.0.1 on 2024-03-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_companygame_livestream_alter_closedate_companyid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='closedate',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
