# Generated by Django 5.0.1 on 2024-03-12 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_closedate_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinationLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combination', models.CharField(max_length=20)),
                ('limit', models.FloatField()),
                ('companyGame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.companygame', verbose_name='CompanyGame')),
            ],
        ),
    ]
