# Generated by Django 5.0.1 on 2024-03-12 08:38

import game.models.company_game
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_combinationlimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='companygame',
            name='storeSettings',
            field=models.JSONField(default=game.models.company_game.CompanyGame.store_settings_default, verbose_name='StoreSettings'),
        ),
    ]
