# Generated by Django 5.0.1 on 2024-03-12 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_companygame_storesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.UUIDField()),
                ('streak', models.IntegerField()),
                ('companyGame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.companygame', verbose_name='CompanyGame')),
            ],
        ),
    ]
