# Generated by Django 5.0.1 on 2024-03-15 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_winstreak'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinationlimit',
            name='companyId',
            field=models.UUIDField(default='3fa85f64-5717-4562-b3fc-2c963f66afa6'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combinationlimit',
            name='gameId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.game', verbose_name='Game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drawresult',
            name='companyGame',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.companygame', verbose_name='CompanyGame'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drawresult',
            name='companyId',
            field=models.UUIDField(default='3fa85f64-5717-4562-b3fc-2c963f66afa6'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameschedule',
            name='companyId',
            field=models.UUIDField(default='3fa85f64-5717-4562-b3fc-2c963f66afa6'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prizepool',
            name='companyId',
            field=models.UUIDField(default='3fa85f64-5717-4562-b3fc-2c963f66afa6'),
            preserve_default=False,
        ),
    ]
