# Generated by Django 5.0.1 on 2024-03-15 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_combinationlimit_companyid_combinationlimit_gameid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='closedate',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.game', verbose_name='Game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamedrawtype',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.game', verbose_name='Game'),
            preserve_default=False,
        ),
    ]
