# Generated by Django 5.0.1 on 2024-03-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_closedate_game_gamedrawtype_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='betitem',
            name='transactionType',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
