# Generated by Django 5.0.1 on 2024-03-20 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0030_betitem_transactiontype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betitem',
            name='betTransaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='betItems', to='game.bettransaction'),
        ),
        migrations.AlterField(
            model_name='betitem',
            name='companyGame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='betItems', to='game.companygame'),
        ),
        migrations.AlterField(
            model_name='betitem',
            name='gameSchedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='betItems', to='game.gameschedule'),
        ),
    ]
