# Generated by Django 5.0.1 on 2024-03-20 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_alter_betitem_bettransaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bettransaction',
            name='orderId',
        ),
    ]
