# Generated by Django 5.0.3 on 2024-03-21 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0032_remove_bettransaction_orderid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='betitem',
            name='transactionType',
        ),
        migrations.RemoveField(
            model_name='bettransaction',
            name='transactionNumber',
        ),
    ]
