# Generated by Django 5.0.3 on 2024-03-21 13:24

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0033_remove_betitem_transactiontype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bettransaction',
            name='transactionRef',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.RawSQL("('HPTRN' || LPAD(id::text, 11, '0'))", ()), output_field=models.TextField()),
        ),
    ]
