# Generated by Django 5.0.3 on 2024-03-21 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0034_bettransaction_transactionref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bettransaction',
            old_name='transactionRef',
            new_name='transactionNumber',
        ),
    ]
