# Generated by Django 5.0.1 on 2024-03-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0035_rename_transactionref_bettransaction_transactionnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameschedule',
            name='drawTime',
            field=models.TimeField(default='13:00:00'),
            preserve_default=False,
        ),
    ]
