# Generated by Django 5.0.3 on 2024-03-31 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0036_gameschedule_drawtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawresult',
            name='gameSchedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.gameschedule', verbose_name='GameSchedule'),
        ),
        migrations.AlterField(
            model_name='prizepool',
            name='gameSchedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.gameschedule', verbose_name='GameSchedule'),
        ),
    ]
