# Generated by Django 5.0.3 on 2024-04-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0037_alter_drawresult_gameschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prizepool',
            name='hasDrawn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prizepool',
            name='hasWinner',
            field=models.BooleanField(default=False),
        ),
    ]
