# Generated by Django 5.0.1 on 2024-04-01 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0037_alter_drawresult_gameschedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bettransaction',
            name='dateOfTransaction',
            field=models.DateTimeField(),
        ),
    ]
