# Generated by Django 5.0.3 on 2024-04-02 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0038_alter_bettransaction_dateoftransaction'),
        ('game', '0038_prizepool_hasdrawn_prizepool_haswinner'),
    ]

    operations = [
    ]
