# Generated by Django 5.0.3 on 2024-04-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0039_merge_20240403_0322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winstreak',
            name='userId',
        ),
        migrations.AddField(
            model_name='winstreak',
            name='accountId',
            field=models.BigIntegerField(default=505),
            preserve_default=False,
        ),
    ]
