# Generated by Django 5.0.1 on 2024-04-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0040_remove_winstreak_userid_winstreak_accountid'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawresultwinner',
            name='isCreditProcessed',
            field=models.BooleanField(default=False),
        ),
    ]
