# Generated by Django 5.0.1 on 2024-04-08 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0041_drawresultwinner_iscreditprocessed'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyId', models.UUIDField()),
                ('result', models.CharField(max_length=30)),
                ('amount', models.FloatField()),
                ('noOfWinners', models.IntegerField()),
                ('noOfQuasiWinners', models.IntegerField()),
                ('isDeleted', models.BooleanField(default=False)),
                ('companyGame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.companygame', verbose_name='CompanyGame')),
                ('gameSchedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.gameschedule', verbose_name='GameSchedule')),
            ],
        ),
    ]
